services:
  postgres:
    image: postgres:latest
    container_name: postgres-wc
    restart: always
    environment:
      POSTGRES_USER: wcuser
      POSTGRES_PASSWORD: wcpass
      POSTGRES_DB: worldcupdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data      # ✅ Persistance automatique
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de création

volumes:
  pgdata:  # Ce volume stockera les données PostgreSQL localement
