# world-cup-bd/docker-compose.yml
services:
  postgres:
    image: postgres:latest
    container_name: postgres-wc
    environment:
      POSTGRES_USER: wcuser
      POSTGRES_PASSWORD: wcpass
      POSTGRES_DB: worldcupdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data          # volume persistant (ok)
      - ./docker/db/backup.sql:/docker-backup.sql:ro  # <-- nouveau

volumes:
  pgdata:
